Hamburgerci.UI/Controllers/EkstraMalzemeController.cs
using Hamburgerci.Application.Models.VMs;
using Hamburgerci.Application.Services.Abstract;
using Hamburgerci.Application.Services.Concrete;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using Hamburgerci.Application.Models.DTOs;
using Microsoft.AspNetCore.Authorization;

namespace Hamburgerci.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EkstraMalzemeController : Controller
    {
        private readonly IEkstraMalzemeService _ekstraMalzemeService;

        public EkstraMalzemeController(IEkstraMalzemeService ekstraMalzemeService)
        {
            _ekstraMalzemeService = ekstraMalzemeService;
        }
        public async Task<IActionResult> Index(string searchText,int pageSize=5, int page=1)
        {
			EkstraMalzemeListingVM vm = new EkstraMalzemeListingVM();
            var ekstraMalzemeler = await _ekstraMalzemeService.GetAll();
            vm.EkstraMalzemeler = ekstraMalzemeler.ToPagedList(pageNumber: page, pageSize: pageSize);

            if(!String.IsNullOrEmpty(searchText) ) 
            {
                ekstraMalzemeler = await _ekstraMalzemeService.Search(searchText);
                vm.EkstraMalzemeler = ekstraMalzemeler.ToPagedList(page,pageSize);
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> EkstraMalzemeEkle(EkstraMalzemeListingVM model)
        {
            if (ModelState.IsValid)
            {
                await _ekstraMalzemeService.Create(model.EkstraMalzeme);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> EkstraMalzemeSil(int id)
        {
            await _ekstraMalzemeService.Delete(id);
            return RedirectToAction("Index");
        }



		//public async Task<IActionResult> EkstraMalzemeDuzenle(int id)
		//{
		//	await _ekstraMalzemeService.GetById(id);
  //          return View();
		//}




		[HttpPost]
        public async Task<IActionResult> EkstraMalzemeDuzenle(EkstraMalzemeDTO model)
        {
            if (ModelState.IsValid) 
            {
                await _ekstraMalzemeService.Update(model);
            }
            return RedirectToAction("Index");
        }







	}
}

Hamburgerci.UI/Views/EkstraMalzeme/Components/EkstraMalzemeEkle/Default.cshtml
@model Hamburgerci.Application.Models.VMs.EkstraMalzemeListingVM

<div class="card shadow">
	<div class="card-header py-3">
		<p class="text-primary m-0 fw-bold">Yeni Ekstra Malzeme Ekle</p>
	</div>
	<div class="card-body">
		<form asp-action="EkstraMalzemeEkle" asp-controller="EkstraMalzeme" method="post">
			<div class="form-group">
				<label asp-for="EkstraMalzeme">Ekstra Malzeme Adı:</label>
				<input type="text" class="form-control" asp-for="EkstraMalzeme.Adi" />
			</div>

			<div class="form-group">
				<label asp-for="EkstraMalzeme.Fiyati">Ekstra Malzeme Fiyatı:</label>
				<input type="number" class="form-control" asp-for="EkstraMalzeme.Fiyati" min="1" />
			</div>
			<button type="submit" class="btn-primary btn-block">Ekle</button>
		</form>
	</div>
	<div class="card-footer">
	</div>
</div>